language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token 
  - npm run coveralls
  - cat ./coverage/lcov.info | node node_modules/.bin/coveralls